opencachefile "../H3MythicMaps/sandbox.map"
porttag ui\chud\assault_rifle.chud_definition
porttag ui\chud\battle_rifle.chud_definition
porttag ui\chud\beam_rifle.chud_definition
porttag ui\chud\brute_shot.chud_definition
porttag ui\chud\carbine.chud_definition
porttag ui\chud\e_bubbleshield.chud_definition
porttag ui\chud\e_flare.chud_definition
porttag ui\chud\e_gravlift.chud_definition
porttag ui\chud\e_instacover.chud_definition
porttag ui\chud\e_jammer.chud_definition
porttag ui\chud\e_powerdrain.chud_definition
porttag ui\chud\e_regen.chud_definition
porttag ui\chud\e_tripmine.chud_definition
porttag ui\chud\elite.chud_definition
porttag ui\chud\excavator.chud_definition
porttag ui\chud\flamethrower.chud_definition
porttag ui\chud\fuel_rod_cannon.chud_definition
porttag ui\chud\golf_club.chud_definition
porttag ui\chud\hammer.chud_definition
porttag ui\chud\machinegun_turret.chud_definition
porttag ui\chud\magnum.chud_definition
porttag ui\chud\missile.chud_definition
porttag ui\chud\monitor.chud_definition
porttag ui\chud\needler.chud_definition
porttag ui\chud\plasma_pistol.chud_definition
porttag ui\chud\plasma_rifle.chud_definition
porttag ui\chud\plasma_turret.chud_definition
porttag ui\chud\rocket.chud_definition
porttag ui\chud\sentinel_beam.chud_definition
porttag ui\chud\shotgun.chud_definition
porttag ui\chud\smg.chud_definition
porttag ui\chud\sniper_rifle.chud_definition
porttag ui\chud\spartan.chud_definition
porttag ui\chud\spartan_laser.chud_definition
porttag ui\chud\spike_rifle.chud_definition
porttag ui\chud\sword.chud_definition
porttag ui\chud\t_machinegun.chud_definition
porttag ui\chud\t_plasmaturret.chud_definition
porttag ui\chud\unarmed.chud_definition
porttag ui\chud\v_banshee.chud_definition
porttag ui\chud\v_chaingun.chud_definition
porttag ui\chud\v_chopper.chud_definition
porttag ui\chud\v_driver.chud_definition
porttag ui\chud\v_gaussturret.chud_definition
porttag ui\chud\v_ghost.chud_definition
porttag ui\chud\v_grinderdriver.chud_definition
porttag ui\chud\v_grinderturret.chud_definition
porttag ui\chud\v_hornet.chud_definition
porttag ui\chud\v_mongoose.chud_definition
porttag ui\chud\v_scorpion.chud_definition
porttag ui\chud\v_scorpionturret.chud_definition
porttag ui\chud\v_wraith.chud_definition
porttag ui\chud\v_wraith_anti_air.chud_definition
porttag ui\chud\v_wraithturret.chud_definition
exit
opencachefile "../H3Maps/100_citadel.map"
porttag ui\chud\e_autoturret.chud_definition
porttag ui\chud\e_invincibility.chud_definition
porttag ui\chud\e_invisibility.chud_definition
exit
quit